name: Generate Keystore

on:
  push:
    paths:
      - '.github/workflows/generate-keystore.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore File
        run: |
          keytool -genkeypair -v \
            -keystore release.keystore \
            -alias my-key-alias \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass android \
            -keypass android \
            -dname "CN=Android Debug, O=Android, C=US"

      - name: Encode Keystore and Print
        run: |
          echo "COPY THE NEW STRING BELOW:"
          echo "=================================================================="
          base64 -w 0 release.keystore
          echo "=================================================================="
          echo "Use 'android' for KEYSTORE_PASSWORD and KEY_PASSWORD"
          echo "Use 'my-key-alias' for KEY_ALIAS"
