name: Generate Keystore Artifact

on:
  push:
    paths:
      - '.github/workflows/generate-keystore-artifact.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore File
        run: |
          keytool -genkeypair -v \
            -keystore release.keystore \
            -alias my-key-alias \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass android \
            -keypass android \
            -dname "CN=Android Debug, O=Android, C=US"

      - name: Upload Keystore as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: keystore-artifact
          path: release.keystore
